name: Brute OS SDDM & SDDM-Theme PKG BUILD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
             git \
             build-essential \
             devscripts \
             debhelper \
             cmake \
             debhelper-compat \
             extra-cmake-modules \
             libpam0g-dev \
             libsystemd-dev \
             libupower-glib-dev \
             libxcb-xkb-dev \
             libxcb1-dev \
             libxkbcommon-dev \
             pkg-config \
             python3-docutils \
             qtbase5-dev \
             qtdeclarative5-dev \
             qttools5-dev \
             qttools5-dev-tools \
             systemd

    - name: Create Directory and pull source repository
      run: |
         mkdir -p /tmp/pkg_build/pkg/
         cd /tmp/pkg_build/
         git clone https://github.com/sys41x4/pkg_build_scripts.git
         git clone https://gitlab.com/brute-os/packages/sddm.git
         cd sddm
         git checkout main
    # Copy your files into the sddm directory

    - name: Generate Debian package
      run: |
        cd /tmp/pkg_build/
        /tmp/pkg_build/pkg_build_scripts/deb/create_unsigned_debian_pkg.sh sddm@all "Arijit Bhowmick" root
        mv /tmp/pkg_build/BUILD_sddm/ /tmp/pkg_build/pkg/

    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sddm
        path: /tmp/pkg_build/pkg/
